#!/bin/sh
set -e

# First install package and exit if fails as it's required for subsequent steps
${package} install iptables || exit 1

# Then deploy file but ensure directory is present
${directory} -d /etc/iptables
${file} -b -s ${STATEDIR}/files/etc/iptables/iptables.rules \
                              -d /etc/iptables/iptables.rules

# Then if successful restart service
${service} -e restart iptables iptables.rules
